import { ExerciseStep } from './types';

const GITHUB_BASE = 'https://raw.githubusercontent.com/alexanderbacca/Yany/main';

export const WORK_SEC = 40;
export const REST_SEC = 20;
export const STORAGE_KEY_SESSIONS = 'yany_sessions';

export const WARMUP_STEPS: ExerciseStep[] = [
  {
    id: 'marcha',
    name: 'Marcha en el lugar',
    description: 'Camina sin moverte del sitio, elevando las rodillas suavemente para elevar la temperatura corporal.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'warmup',
    imageUrl: `${GITHUB_BASE}/Marcha.webp`,
  },
  {
    id: 'circulos-brazos',
    name: 'Círculos de brazos',
    description: 'Con los brazos extendidos a los lados, dibuja círculos pequeños hacia adelante y luego hacia atrás.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'warmup',
    imageUrl: `${GITHUB_BASE}/CirculosBrazos.webp`,
  },
  {
    id: 'rotacion-cadera',
    name: 'Rotaciones de cadera',
    description: 'Manos en la cintura, dibuja círculos amplios y lentos con la cadera en ambas direcciones.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'warmup',
    imageUrl: `${GITHUB_BASE}/RotacionCadera.webp`,
  },
  {
    id: 'elevacion-talones',
    name: 'Elevaciones de talones',
    description: 'Elévate sobre las puntas de los pies y baja con control. Puedes apoyarte en una silla para mantener el equilibrio.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'warmup',
    imageUrl: `${GITHUB_BASE}/ElevacionTalones.webp`,
  },
  {
    id: 'rotacion-torso',
    name: 'Rotaciones de torso',
    description: 'Con los pies al ancho de la cadera, gira el torso suavemente de un lado al otro.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'warmup',
    imageUrl: `${GITHUB_BASE}/RotacionTorso.webp`,
  },
  {
    id: 'sentadilla-suave',
    name: 'Sentadilla parcial suave',
    description: 'Flexiona ligeramente las rodillas en una sentadilla parcial, manteniendo las rodillas detrás de la punta de los pies.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'warmup',
    imageUrl: `${GITHUB_BASE}/SentadillaSuave.webp`,
  },
];

export const CIRCUIT_STEPS: ExerciseStep[] = [
  {
    id: 'sentadilla-silla',
    name: 'Sentadilla a la silla',
    description: 'Siéntate y levántate de la silla de forma lenta y controlada, sin usar las manos si puedes.',
    target: '10–15 repeticiones',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/SentadillaSilla.webp`,
  },
  {
    id: 'flexiones-inclinadas',
    name: 'Flexiones inclinadas en silla',
    description: 'Apoya las manos en el asiento de la silla y flexiona los codos manteniendo el cuerpo en línea recta.',
    target: '8–12 repeticiones',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/FlexionesInclinadas.webp`,
  },
  {
    id: 'puente-gluteos',
    name: 'Puente de glúteos',
    description: 'Acostada boca arriba en la colchoneta, eleva la cadera apretando los glúteos en la parte alta del movimiento.',
    target: '12–15 repeticiones',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/PuenteGluteos.webp`,
  },
  {
    id: 'marcha-rodillas',
    name: 'Marcha elevando rodillas',
    description: 'Marcha de bajo impacto elevando las rodillas a la altura de la cadera, con ritmo constante.',
    target: '40 segundos',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/MarchaRodillas.webp`,
  },
  {
    id: 'plancha-rodillas',
    name: 'Plancha con rodillas',
    description: 'Plancha sobre los antebrazos con las rodillas apoyadas en la colchoneta y la espalda recta.',
    target: '20–40 segundos',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/PlanchaRodillas.webp`,
  },
  {
    id: 'abdominales-cortos',
    name: 'Abdominales cortos',
    description: 'Abdominales pequeños y controlados: prioriza la calidad sobre la velocidad, con la zona lumbar apoyada en la colchoneta.',
    target: '10–15 repeticiones',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/AbdominalesCortos.webp`,
  },
  {
    id: 'perro-caza',
    name: 'Perro de caza',
    description: 'En cuatro puntos sobre la colchoneta, extiende al mismo tiempo el brazo y la pierna opuestos, manteniendo el equilibrio.',
    target: '8 repeticiones por lado',
    durationSec: 40,
    kind: 'main',
    imageUrl: `${GITHUB_BASE}/PerroCaza.webp`,
  },
];

export const COOLDOWN_STEPS: ExerciseStep[] = [
  {
    id: 'estiramiento-cuadriceps',
    name: 'Estiramiento de cuádriceps',
    description: 'De pie y sujetándote de la silla, lleva un talón hacia el glúteo para estirar el cuádriceps.',
    target: '15 segundos por pierna',
    durationSec: 30,
    kind: 'cooldown',
    imageUrl: `${GITHUB_BASE}/EstiramientoCuadriceps.webp`,
  },
  {
    id: 'estiramiento-isquiotibiales',
    name: 'Estiramiento de isquiotibiales',
    description: 'Apoya el talón sobre la silla e inclínate suavemente hacia adelante con la espalda recta.',
    target: '15 segundos por pierna',
    durationSec: 30,
    kind: 'cooldown',
    imageUrl: `${GITHUB_BASE}/EstiramientoIsquiotibiales.webp`,
  },
  {
    id: 'apertura-pecho',
    name: 'Apertura de pecho',
    description: 'Entrelaza los dedos detrás de la espalda y abre el pecho elevando ligeramente los brazos.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'cooldown',
    imageUrl: `${GITHUB_BASE}/AperturaPecho.webp`,
  },
  {
    id: 'postura-nino',
    name: 'Postura del niño',
    description: 'Arrodíllate en la colchoneta, extiende los brazos al frente y relaja la espalda.',
    target: '30 segundos',
    durationSec: 30,
    kind: 'cooldown',
    imageUrl: `${GITHUB_BASE}/PosturaNino.webp`,
  },
  {
    id: 'estiramiento-lateral',
    name: 'Estiramiento lateral',
    description: 'De pie, con un brazo por encima de la cabeza, inclínate suavemente hacia el lado contrario.',
    target: '15 segundos por lado',
    durationSec: 30,
    kind: 'cooldown',
    imageUrl: `${GITHUB_BASE}/EstiramientoLateral.webp`,
  },
  {
    id: 'respiracion',
    name: 'Respiración profunda',
    description: 'Inhala por la nariz durante 4 segundos y exhala por la boca durante 6 segundos, de forma lenta y controlada.',
    target: '5 respiraciones',
    durationSec: 30,
    kind: 'cooldown',
    imageUrl: `${GITHUB_BASE}/Respiracion.webp`,
  },
];
